# Generated by Django 2.2.3 on 2021-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, null=True)),
                ('opción1', models.CharField(max_length=200, null=True)),
                ('opción2', models.CharField(max_length=200, null=True)),
                ('opción3', models.CharField(max_length=200, null=True)),
                ('opción4', models.CharField(max_length=200, null=True)),
                ('respuesta_correcta', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
