# Generated by Django 2.2.3 on 2021-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='op1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
