# Generated by Django 2.2.3 on 2021-08-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia', '0002_auto_20210824_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='ans',
            new_name='opción1',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='op1',
            new_name='opción2',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='op2',
            new_name='opción3',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='op3',
            new_name='opción4',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='op4',
            new_name='pregunta',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='question',
            new_name='respuesta_correcta',
        ),
    ]
